# This workflow will build GingerSpec using Maven and then publish it to Maven central when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-apache-maven

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setting up Java 11
      uses: joschi/setup-jdk@v2
      with:
        java-version: 11
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip=true

    - name: Set up Apache Maven Central
      uses: joschi/setup-jdk@v2
      with: # running setup-java again overwrites the settings.xml
        java-version: 11
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Publish to Apache Maven Central
      run: mvn clean deploy -P sign,build-extras -Dmaven.test.skip=true
      env:
        MAVEN_USERNAME: jose.fernandez
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Performing a dry-run to generate pages
      run: mvn clean verify -Dcucumber.execution.dry-run=true

    - name: Publish pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        folder: target/documentation
