# This workflow will build GingerSpec with maven and execute all integration tests in 3 different openjdk versions

name: GingerSpec pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        java: [11, 17, 19]
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: mysql
        ports:
        - 3306:3306
      postgres:
        image: postgres:9.6.8
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
      clickhouse:
        image: dmamontov/gingerspec-clickhouse:1.0
        ports:
        - 8123:8123
      rest-server:
        image: privaliatech/privalia-rest-server:0.1.0
        ports:
        - 3000:3000
      graphql-server:
        image: dmamontov/gingerspec-graphql:1.0
        ports:
        - 3001:3000
      oas2-server:
        image: dmamontov/gingerspec-oas:2
        ports:
        - 3002:4010
      oas3-server:
        image: dmamontov/gingerspec-oas:3
        ports:
        - 3003:4010
      demo-site:
        image: josefd8/selenium-testpages-image:1.0
        ports:
        - 4567:4567
      selenium-grid:
        image: selenium/hub:3.141.59-20210311
        ports:
        - 4444:4444
      selenium-chrome:
        image: selenium/node-chrome:3.141.59-20210311
        env:
          HUB_HOST: selenium-grid
          HUB_PORT: 4444
        options: -v /dev/shm:/dev/shm
    steps:
    - uses: actions/checkout@v3
    - name: Setting up Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
            ${{ runner.os }}-maven-
    - name: Building with Maven
      run: mvn clean install -DVERSION=1.0 -DSLEEPTEST=3 -DAGENT_LIST=1,2 -DVARNAME=foo -DWAIT=1 -DPOSTGRES_HOST=localhost -DMYSQL_HOST=localhost -DCLICKHOUSE_HOST=localhost -DREST_SERVER_HOST=localhost -DGRAPHQL_SERVER_HOST=localhost -DDEMO_SITE_HOST=demo-site:4567 -DSELENIUM_GRID=http://localhost:4444/wd/hub -DZOOKEEPER_HOST=localhost -DSCHEMA_REGISTRY_HOST=localhost
