# This workflow will build GingerSpec using Maven and then publish it to Maven central when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-apache-maven

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set upJava 11 with Apache Maven Central
      uses: actions/setup-java@v3
      with: # running setup-java again overwrites the settings.xml
        java-version: 11
        distribution: 'temurin'
        cache: maven
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: ${{ secrets.MAVEN_USERNAME }} # env variable for username in deploy
        server-password: ${{ secrets.MAVEN_CENTRAL_TOKEN }} # env variable for token in deploy
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }} # env variable for GPG private key passphrase
        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2

    - name: Build with Maven
      run: mvn clean package -Dmaven.test.skip=true

    - name: Publish to Apache Maven Central
      run: mvn clean deploy -P sign,build-extras -Dmaven.test.skip=true
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Performing a dry-run to generate pages
      run: mvn clean verify -Dcucumber.execution.dry-run=true

    - name: Publish pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        folder: target/documentation
