# This is a test workflow for publishing the documentation to github pages

name: Publish pages

on:
  release:
    types: [created]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: write

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Set upJava 11 with Apache Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Performing a dry-run to generate pages
        run: mvn clean verify -Dcucumber.execution.dry-run=true

      - name: Publish pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: target/documentation
